Repository hmcts/ccpay-notifications-service, pull requests merged in 2023-12, with the labels that each got.

#252 PAY-6713 amend original vault values to pickup flexible DB
  build.gradle
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-notifications-service-pr-252

#255 PAY-6715: Update to fix/suppress dependencies
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-255

#257 PAY-6746 logback
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-257

#260 PAY-6659 notification db decommissioned
  charts/ccpay-notifications-service/Chart.yaml
  charts/ccpay-notifications-service/values.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, destroy, rel:ccpay-notifications-service-pr-260

#262 PAY-6756 owasp upgrade
  build.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-262
