Repository hmcts/ccpay-notifications-service, pull requests merged in 2023-03, with the labels that each got.

#136 update azurerem version
  infrastructure/state.tf
Labels: ns:fees-pay, prd:ccpay, no-changes, rel:ccpay-notifications-service-pr-136

#137 upgrading java charts and commons fileupload to v1.5
  charts/ccpay-notifications-service/Chart.yaml
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-137

#138 damages add in service contact
  src/main/resources/db/changelog/db.changelog-0.5.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-138

#142 FT pointing to localhost for test.
  src/functionalTest/resources/application-functional.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-142

#144 Ft fix nightly dev
  Jenkinsfile_nightly
  audit.json
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-144

#147 suppressed new cve
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-147

#148 Initial PR change
  config/owasp/suppressions.xml
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-148

#149 PAY-4884: Update Chart Java to latest version
  charts/ccpay-notifications-service/Chart.yaml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-149
