Repository hmcts/ccpay-notifications-service, pull requests merged in 2023-10, with the labels that each got.

#196 PAY-6592-CVE-2023-0833 suppressed.
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-196

#224 version update
  charts/ccpay-notifications-service/Chart.yaml
  charts/ccpay-notifications-service/values.yaml
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-224

#231 PAY-6629-Flexible Server db created
  infrastructure/main.tf
  infrastructure/provider.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:ccpay, add-or-update, rel:ccpay-notifications-service-pr-231

#242 PAY-6629-Flexible Server db renamed
  infrastructure/main.tf
Labels: ns:fees-pay, prd:ccpay, destroy, rel:ccpay-notifications-service-pr-242
