Repository hmcts/ccpay-notifications-service, pull requests merged in 2023-06, with the labels that each got.

#160 CVE-2023-28709
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-160

#161 fix cves
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-161

#162 fix cves
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-162

#163 CVE expiry update
  config/owasp/suppressions.xml
Labels: ns:fees-pay, prd:ccpay, rel:ccpay-notifications-service-pr-163
